tasty_bytes:
  target: dev
  outputs:
    int-dev:
      type: snowflake
      account: fazzqud-uk26639
      user: TOFANSAHOO
      password: MiltonKeynesDBT6798@
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: int-dev
      warehouse: tasty_bytes_dbt_wh
      threads: 8
    dev:
      type: snowflake
      account: fazzqud-uk26639
      user: TOFANSAHOO
      password: MiltonKeynesDBT6798@
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh
      threads: 8
